### ISSUE TITLE
Messaging Exception : Connection Refused

### ISSUE THREAD

**Issue by r0hi7** [r0hi7/Trashemail#3]
**Describe the bug**
The log shows the messaging exception.
```
javax.mail.MessagingException: Connection refused (Connection refused);
  nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:665)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:196)
	at io.github.trashemail.EmailInteraction.ImapClient.ensureOpen(ImapClient.java:155)
	at io.github.trashemail.EmailInteraction.ImapClient$IdleThread.run(ImapClient.java:115)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:288)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.iap.Protocol.<init>(Protocol.java:113)
	at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:110)
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:632)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 1.0.0

**Comment by r0hi7** [comment]
Tested and confirmed this is more of network issue.
