### ISSUE TITLE
BYE server shutdown

### ISSUE THREAD

**Issue by r0hi7** [r0hi7/Trashemail#4]
**Describe the bug**
```
javax.mail.FolderClosedException: * BYE Server shutting down.
	at com.sun.mail.imap.IMAPFolder.throwClosedException(IMAPFolder.java:2538)
	at com.sun.mail.imap.IMAPFolder.idle(IMAPFolder.java:2336)
	at com.sun.mail.imap.IMAPFolder.idle(IMAPFolder.java:2252)
	at io.github.trashemail.EmailInteraction.ImapClient$IdleThread.run(ImapClient.java:117)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 1.0.0

**Comment by r0hi7** [comment]
I am still not able to understand the way to resolve this folder closed exception.

**Comment by r0hi7** [comment]
This exception is still coming up in the logs due to which the emails are not getting processed.

**Comment by r0hi7** [comment]
This issues is happening around this file: EmailsToTelegramService/src/main/java/io/github/trashemail/EmailsToTelegramService/ImapClient.java
Is there any other way of polling imap in java, which is more reliable than the current approach?

**Comment by r0hi7** [comment]
@susam can you help with this ?

**Comment by r0hi7** [comment]
I believe @nishitm have smartly fixed this issue in which he identified the root cause of this issue and made a simple solution by sending dummy NOOPS to the server to keep the connection open. Thanks you so much for making this service more reliable @nishitm 😄
